#!/usr/bin/env bash

basedir="$(dirname "$0")"
. "$basedir/include.sh"

files_dir=$1

results_dir="results"

processes=4

if [ $# -ge 2]; then
	processes=$2
fi

if [ $# -ge 3]; then
	processes=$3
fi

rg -F "tff" --files-with-matches $files_dir | xargs -P $processes -I {} sh -c 'time ("$basedir/check_tptp.sh" % > "results/$(basename %)") 2>> "$results_dir/$(basename %)"'
